<div id="circulo">
			<ul class="simple">
			<li><a href="#">Cursos</a></li>
			<li><a href="#">Cultura</a></li>
			<li><a href="#">Musica</a></li>
			<li><a href="#">Danza</a></li>
			<li><a href="#">Temazcal</a></li>
			<li><a href="#">Gastronomia Prehispanica</a></li>
			<li><a href="#">Filosofia Ancestral</a></li>
			<li><a href="#">Cosmologia</a></li>
			<li><a href="#">descargas</a></li>
			<li><a href="#">libros</a></li>
			<li><a href="#">audio</a></li>
			<li><a href="#">Tonalpuhuali</a></li>
			<li><a href="#">artesanias</a></li>
			<li><a href="#">Parajes</a></li>
			<li><a href="#">fauna de Milpa Alta</a></li>
			<li><a href="#">Flora de Milpa Alta</a></li>
			<li><a href="#">Tradiciones</a></li>
			<li><a href="#">Milpa Alta en la Historia</a></li>
			<li><a href="#">vocabulario</a></li>
			<li><a href="#">pueblos originarios</a></li>
			<li><a href="#">Ohtenco</a></li>
			<li><a href="#">Cuauhtenco</a></li>
			<li><a href="#">Oztotepec</a></li>
			<li><a href="#">xicomulco</a></li>
			<li><a href="#">Actopan</a></li>
			<li><a href="#">Tecozpa</a></li>
			<li><a href="#">Tecomitl</a></li>
			<li><a href="#">tepenahuac</a></li>
			<li><a href="#">Tlacotenco</a></li>
			<li><a href="#">Miacatlan</a></li>
			<li><a href="#">tlacoyucan</a></li>
			<li><a href="#">Malacaxtepec Momoxco</a></li>
			<li><a href="#">Siembra</a></li>
			<li><a href="#">Poesia</a></li>
			<li><a href="#">Cuentos</a></li>
			<li><a href="#">Leyendas</a></li>
			<li><a href="#">sitios Turisticos</a></li>
			</ul>
</div>
<div id="sol"></div>